server:
  port: 82


eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8090/eureka
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
    #hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-curso-service
          uri: lb://ms-curso-service
          predicates:
            - Path=/curso/**
        - id: ms-calificacion-service
          uri: lb://ms-calificacion-service
          predicates:
            - Path=/calificacion/**
        - id: ms-conducta-service
          uri: lb://ms-conducta-service
          predicates:
            - Path=/conducta/**
        - id: ms-gestionestudiantes-service
          uri: lb://ms-gestionestudiantes-service
          predicates:
            - Path=/estudiante/**, /historialacadémico/**
        - id: ms-gestiondocentes-service
          uri: lb://ms-gestiondocentes-service
          predicates:
            - Path=/asignatura/**, /docente/**
        - id: ms-monitoreoasistencia-service
          uri: lb://ms-monitoreoasistencia-service
          predicates:
            - Path=/registroasistencia/**
        - id: ms-reporte-service
          uri: lb://ms-reporte-service
          predicates:
            - Path=/reportes/**
        - id: ms-matriculas-service
          uri: lb://ms-matriculas-service
          predicates:
            - Path=/horarios/**, /matriculas/**
          filters:
            - AuthFilter
        - id: ms-auth-service
          uri: lb://ms-auth-service
          predicates:
            - Path=/auth/**





